

# Linux driver folder

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/himax_852xES/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+= himax_platform.o 
obj-y	+= himax_852xES.o
