# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y   +=  accel.o accel_factory.o


obj-$(CONFIG_MTK_BMA222E_NEW)   +=  bma222E-new/

